name: chat_project

services:
  postgres:
    image: postgres:17.2
    container_name: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - chat_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - chat_network
    volumes:
      - redis_data:/data

networks:
  chat_network:

volumes:
  postgres_data:
  redis_data:
